### ISSUE TITLE
Enter sign-up page and sign up as student or tutor

### ISSUE THREAD

**Issue by OrangeRoof** [cs130-w21/bruintutor#11]
## User Story
As a user who is student or tutor, I would like to be able to visit a sign-up page and register myself to the website.

## Detailed Description
This story should cover all related technologies required to setup a sign-in page. First, an interactive html page will be created to provide an interface for the user. A database will be created to store relevant information about users. An nginx/uwsgi server will host the website and provide communication to python code. Sqlalchemy will also be used to store http signup requests into the database. Also included in this story is tasks related to the setup of environment and CI/CD. 

## Acceptance Criteria
- [x] Given I am a person without an account, then I am able to sign up for the website with my name and email by filling in the information, indicating what type of person I am, and then clicking sign up
- [x] Given I am a student, I should be able to register as a student with the system
- [x] Given I am a tutor, I should be able to register as a tutor in the system
- [x] Given that I have done the steps above, the website should tell me that I have an account with which I can now sign in.

## Tasks
- [x] Create a html sign up page to input name, tutor/student
- [x] develop redis to store information
- [x] set up nginx/uwsgi to forward http requests to python #50
- [x] set up travisci.org #49
- [x] set up redis to store http signup request into database
- [x] create unit test framework for backend testing

**Comment by sammyli0106** [comment]
Done
