### ISSUE TITLE
Create Search Page Layout

### ISSUE THREAD

**Issue by davisgomes** [cs130-w21/bruintutor#13]
## User Story
As a user, I would like to interact with the search page so that I am able to locate tutors and students relating to my search criteria.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given the page is loaded, then display a page that hosts search results.
- [ ] Given a user wants to begin searching, then produce a search bar that can be interacted with.
- [ ] Given a user wants to return to profile page, then produce a button that brings them to their profile.
- [ ] Given a user wants to check notification, then produce a button that displays their notifications.

## Tasks
- [x] Create a sidebar to select filters #95
- [x] Create a grid of tutors as search result #96
