### ISSUE TITLE
Student can enter basic information into our website

### ISSUE THREAD

**Issue by OrangeRoof** [cs130-w21/bruintutor#14]
## User Story
As either a student or tutor, I should be able to enter basic information such as my year, major, contact information.

## Detailed Description
A student should be able to add and edit their basic information on their profile page. This will allow customization of useful information that will make searching and matching easier. Students will be able to give year major, classes and contact information to be placed on their page. 

## Acceptance Criteria
- [ ] Given my year, major, and contact information, I should be able to upload this information into my profile page
- [ ] The system should save my profile information, and display it back to me on my profile page.

## Tasks
- [x] create base html page #57 
- [x] add textboxes to be able to enter year, major, contact info #57 
- [x] make textboxes send info to endpoint #55 
- [x] create flask endpoint for profile page page #79 #78
