### ISSUE TITLE
Students can View Profile

### ISSUE THREAD

**Issue by zhao19991111** [cs130-w21/bruintutor#17]
## User Story
As a Student, I would like see my personal information on the profile page so that I can keep track of it.

## Detailed Description
Students should be able to see their major, year, name on the profile page.
Students should be able to see their weekly schedule on the profile page.
Students should be able to handle the visibility of their information on the profile page. 

## Acceptance Criteria
- [x] Given the user is the owner of the profile page, then the user should be able to see all the user information.
- [x] Given the user is not the owner of the profile page, then the user should only be able to see all the visible (public) information.

## Tasks
- [x] create base profile page #41 
- [x] add textboxes to be able to view profile traits #42
- [x] make textboxes grab info from endpoint #43
- [x] created flask endpoint for profile page, need more stuffs to be done #78 
- [x] integrated the scrape classes code into the frontend and backend #81 #82
