### ISSUE TITLE
Tutors can view profile

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#20]
## User Story
As a Tutor, I would like view my profile page so that I can confirm its information and see their current and past students.

## Detailed Description
Tutors should be able to view details about their own tutor page. This will give tutors insight into how other people view their page. This will give a list of aspects about the tutor including current students, past students, schedule, rating, and other profile elements. 

## Acceptance Criteria
- [x] Given a tutor is on their profile page, then they should be able to see their profile, the list of current students, and the list of past students

## Tasks
- [x] Create HTML page for profiles #44
- [x] add textboxes to be able to view profile info #45
- [x] make textboxes grab profile info from endpoint #46
- [x] create flask endpoint to retrieve profiles #79
- [x] create function to retrieve students based on tutor id, tutor can viewed a current/past list of tutored students #80
