### ISSUE TITLE
Display Search Results

### ISSUE THREAD

**Issue by davisgomes** [cs130-w21/bruintutor#25]
## User Story
As a user, I would like tutors to be displayed based on the search criteria so that I can interact with and view all of the recommended tutors and students.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given search criteria, then produce panels of tutors and students that fit the description
- [ ] Given a user wants to view a specific tutor or student page, then allow users to click panels to bring them to that individual's page

## Tasks
- [x] Show a list of Tutors as the search result #96 
- [x] Backend generate a list of Tutors based on search filter parameters #114
