### ISSUE TITLE
Create Scheduling Layout

### ISSUE THREAD

**Issue by GeraldDT5** [cs130-w21/bruintutor#26]
## User Story
As a tutor, I would like to be able to view students who have requested a pairing so that I can check whether their availability matches mine.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given a matching request, then a tutor should be able to click on the potential student's profile
- [ ] Given a matching request, then a tutor should be able to view the potential student's availability
- [ ] Given a tutor is viewing a student's profile, then the tutor should be able to see where availability overlaps

## Tasks
- [x] Implement scheduling interfaces in the search side bar and editor card #103 
- [x] Implement scheduling interfaces in the profile page #112 
- [x] Create requests to retrieve and update user's schedules 
- [x] Create endpoints to return requested user's schedules #115
