### ISSUE TITLE
Render User Page

### ISSUE THREAD

**Issue by davisgomes** [cs130-w21/bruintutor#3]
## Epic
Description and user Benefit:
This will allow the user to interact with the application from a user perspective. Potential users will be able to engage with the searching and matching functionalities. This will also include the front-end design of the application.

User Actions:

- user will be able to search for potential tutors using the dedicated search bar
- user will be able to browse tutoring options using the search results layout
- the user will be able to view individual tutors
- the user will be able to engage in matching with tutors
- the user will be able to view message and match notifications through the notification window

## User Stories
- [x] Create Search Page Layout #13
- [x] Create Individual Tutor View Layout #22
- [x] Display Search Results #25
- [x] Develop Notification Window #32

**Comment by sammyli0106** [comment]
All linked with closed pull requests.
