### ISSUE TITLE
Develop Notification Window

### ISSUE THREAD

**Issue by davisgomes** [cs130-w21/bruintutor#32]
## User Story
As a user, I would like to view my notification window so that I can stay up to date on relevant notifications pertaining to matching.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given an update about matching, then display necessary information within the notification window. #111 
- [x] Given a user wants to view notifications, then produce a button that will allow them to open the notification window. #111 
- [ ] Given a notification is pending view, then produce a signal that notifications are pending. #111
