### ISSUE TITLE
Edit classes

### ISSUE THREAD

**Issue by zhao19991111** [cs130-w21/bruintutor#35]
## User Story
As a Student, I would like edit my classes so that I could keep track of the classes I have taken (am taking).

## Detailed Description
Students should be able to add new classes to their class lists
Students should be able to delete classes from their class lists
Students should be able to edit the name classes in their class lists

## Acceptance Criteria
- [ ] Given the user is a student, then the user should be able to perform above operations on the class list

## Tasks
- [ ] Create UI for user to edit and modify the classes #74 
- [ ] Create backend flask endpoint to update/save classes in the database

**Comment by sammyli0106** [comment]
Duplicate Story. Combined to Story #29
