### ISSUE TITLE
User should be able to log in

### ISSUE THREAD

**Issue by OrangeRoof** [cs130-w21/bruintutor#36]
## User Story
As a User, I would like to log in so that I can use the website.

## Detailed Description
Users should be able to insert their user identification information into the prompted username and password boxes. If they enter a valid username and password, then they should be granted access to that user profile and the attributes that encompass that user. If an incorrect username and password is entered, prompt the user to try again.

## Acceptance Criteria
- [x] user is able to insert login information and gain access to the website
- [x] if user types incorrect username and password combination, prompt them to try again

## Tasks
- [x] create html page for log in
- [x] add ability to send login info to endpoint #47 
- [x] create flask endpoint for log in page #66

**Comment by sammyli0106** [comment]
Reopen for extended Sprint 1
