### ISSUE TITLE
User can sign up as either a student or a tutor

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#6]
## Epic
Users will be able to sign up for the website as either a student or a tutor. Users will then be prompted to input basic information, and optional supplemental information based on if they are a student or tutor.

User Actions

- users will be able to sign up as either a student or a tutor
- users will be able to enter basic information such as name, class, and major
- student users will be able to optionally list classes they are taking
- tutor users will be able to optionally list classes they are willing to tutor for
- tutor users will be able to optionally list their availability

## User Stories
- [x] Enter sign-up page and sign up as student or tutor #11 
- [x] Enter basic information #14
- [x] List classes they are taking #19
- [x] List classes they can tutor for  #24
- [x] User Can login #36
