### ISSUE TITLE
View and customize student profile after signing up

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#7]
## Epic
Student users will be able to view and edit their profile after signing up. This includes adding/removing classes, changing their class and major, and viewing the tutors they are currently working with.

User Actions

- users will be able to view their profile
- users will be able to view the profiles of tutors they are currently working with
- users will be able to edit their name, class, and major
- users will be able to edit the classes they are taking

## User Stories
- [x] View profile #17 
- [x] View profiles of current tutors #23 
- [x] Edit name, class, and major #29 
- [x] Edit classes they are taking #29

**Comment by sammyli0106** [comment]
Tested Student Profile Page
