### ISSUE TITLE
View and customize tutor profile after signing up

### ISSUE THREAD

**Issue by pufan1998** [cs130-w21/bruintutor#8]
## Epic
Tutor users will be able to view and edit their profile after signing up. This includes adding/removing classes they can tutor, changing their class and major, and viewing the students they are currently working with.

User Actions

- users will be able to view their profile
- users will be able to view the profiles of students they are currently working with
- users will be able to edit their name, class, and major
- users will be able to edit the classes they are willing to tutor
- users will be able to edit the availability when they can tutor

## User Stories
- [x] View profile #20 
- [x] View profiles of current students #21 
- [x] Edit name, class, and major #28 
- [x] Edit classes they can tutor #28 
- [x] Edit availability #27

**Comment by sammyli0106** [comment]
Tested Tutor profile page
